<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Platforms>AnyCPU</Platforms>
    <Version>1.0.0</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="WidgetSetup\\**" />
    <EmbeddedResource Remove="WidgetSetup\\**" />
    <None Remove="WidgetSetup\\**" />
    <Page Remove="WidgetSetup\\**" />
    <ApplicationDefinition Remove="WidgetSetup\\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.71.0" />
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.70.0.3819" />
  </ItemGroup>

  <ItemGroup>
    <None Update="credentials.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Update="Update-Windows.ps1" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
